### ISSUE TITLE
message_t::size does not report used buffer size

### ISSUE THREAD

**Issue by cowo78** [xdrpp/xdrpp#14]
The xdr::msg_ptr buffer size is always reported as actual (used) buffer size even if only a fraction of it is really used. Let's say you have a structure like

    struct mymessage {
        string channel<24>;
        uint32_t cycle_id;
        int32_t force;
        uint32_t distance;
    };

compiled by xdrc in the relevant C++ code, plus an
    xdr::msg_ptr buf {xdr::message_t::alloc(36)};

The message size accounts for the maximum string length, but the actual string length may be less than the defined maximum. In any case the serialized message is a fixed 36 + 4 header bytes, thus wasting space. Am I missing something or this is the intended behaviour?
This causes, i.e. problems with Python xdrlib, besides the obvious efficiency/performance issues.

**Comment by stanford-scs** [comment]
xdrpp makes it easy to compute the actual marshaled size of a data structure using `xdr_size`.   Hence, the intended usage is that you allocate the right amount of space and don't waste any memory.  In particular, `xdr_to_message` will just return an appropriately sized buffer containing your marshaled data structure (or data structures, since you can pass in several to have them marshaled back-to-back).
