### ISSUE TITLE
Using enum class for enums in .h files

### ISSUE THREAD

**Issue by vogel** [xdrpp/xdrpp#9]
What about adding a little extra type safety by changing generated code from enum [name] to enum class [name]?

Should be simple to implement (gen_hh.cc:256 maybe?). I can do it if it makes sense to you.

**Comment by stanford-scs** [comment]
Using old-style enums was an intentional design decision, because of how XDR is specified.  XDR does not allow two enum types with conflicting enumerator names, and more importantly does not allow scoping of enumerator names.  So when processing a standard XDR file (like say, the NFS protocol), the compiler would need to infer what scope to add to an enumerator, which will not be possible in the case that one .x file %#includes the generated output of another .x file.
